### ISSUE TITLE
Bug: building a package randomly fails

### ISSUE THREAD

**Issue by liam-ly** [yairchu/macos11-haskell-workaround#1] opened 2020-12-11 19:42 UTC
This project https://github.com/Simspace/ld-wrapper-macos works around a long-standing issue on macOS with projects containing many packages. As is, the test project does not compile on Big Sur and fails with
```
ld: library not found for -liconv
```
See also https://github.com/Simspace/ld-wrapper-macos/issues/6. I was trying to resolve this issue by using this repo's linking workaround.

_This ticket is about the fact that building packages is flaky_. Without the ld-wrapper workaround script enabled,
```
DYLD_INSERT_LIBRARIES=`pwd`/macos11ghcwa.dylib stack build panic
```
results in a flaky `Process exited with code: ExitFailure (-6)` failure. Re-running the build will get past this error and fail on a different package in the same way.

_Note: I updated this ticket from the original description to reduce the scope to a specific issue_

**Comment by joprice** [comment] 2020-12-12 04:05
Same here. I had to run stack 5 or six times before it built.

**Comment by yairchu** [comment] 2020-12-12 18:08
What are the exact repro instructions?

So far I have:

* Clone `ld-wrapper-macos`
* Run its `en-stack-mega-repo.sh`
* Uncomment the `when:` clause `panic/package.yaml` 
* In `panic`, run `stack build`

I get a different error for those steps:

```
yairchu@Yairs-M1-MBP panic % stack build
panic> configure (lib)
panic> Configuring panic-0.0.0...
panic> clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
panic> build (lib)
panic> Preprocessing library for panic-0.0.0..
panic> Building library for panic-0.0.0..
panic> [3 of 3] Compiling Lib
panic> clang: error: invalid linker name in argument '-fuse-ld=ld-wrapper-macos.sh'
panic> `gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package panic-0.0.0 (scroll up to its section to see the error) using:
      /Users/yairchu/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.1.0 build lib:panic --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by liam-ly** [comment] 2020-12-12 20:29
Apologies for the confusion; the behavior is present with the `when:` clause is commented out. I'm only taking advantage of the fact that this project has so many packages, not the script itself yet. When I am able to show that the ld-wrapper-macos script fails at the final linking time, I will file a separate ticket.

`package.yaml`
```
name: panic

#when:
#  - condition: os(darwin)
#    ghc-options:
#      - -optl-fuse-ld=ld-wrapper-macos.sh

...
```

```
% DYLD_INSERT_LIBRARIES=`pwd`/macos11ghcwa.dylib stack build panic -j0
module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001> configure (lib)
module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001> Configuring module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001-0.0.0...
module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001> clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
Progress 1/751

--  While building package module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001-0.0.0 (scroll up to its section to see the error) using:
      /Users/liam/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.1.0 configure --user --package-db=clear --package-db=global --package-db=/Users/liam/.stack/snapshots/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/pkgdb --package-db=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/pkgdb --libdir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/lib --bindir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/bin --datadir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/share --libexecdir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/libexec --sysconfdir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/etc --docdir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/doc/module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001-0.0.0 --htmldir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/doc/module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001-0.0.0 --haddockdir=/Users/liam/Work/ld-wrapper-macos/panic/.stack-work/install/x86_64-osx/f98914bbf0a69f7dc9a3d6635398be4b3227dd006080d0496232b277a98abebc/8.2.2/doc/module0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001-0.0.0 --dependency=base=base-4.10.1.0 --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure (-6)
```

**Comment by joprice** [comment] 2020-12-12 21:06
To be clear, I got this by running stack build on a different project, https://github.com/andyarvanitis/purescript-native, so it could be a different issue:

My stack version

```
stack --version
2.5.1 x86_64 hpack-0.34.2
```

```
Building all executables for `pscpp' once. After a successful build of all of them, only specified executables will be rebuilt.
pscpp> configure (lib + exe)
Configuring pscpp-0.1.0.0...

--  While building package pscpp-0.1.0.0 (scroll up to its section to see the error) using:
      /Users/josephprice/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/Users/josephprice/.stack/snapshots/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/pkgdb --package-db=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/pkgdb --libdir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/lib --bindir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/bin --datadir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/share --libexecdir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/libexec --sysconfdir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/etc --docdir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/doc/pscpp-0.1.0.0 --htmldir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/doc/pscpp-0.1.0.0 --haddockdir=/Users/josephprice/purescript-native/.stack-work/install/x86_64-osx/0be0677209d36cd543a40d9bd743c9722c24ed8b154fff1fc670286ed95eb876/8.6.5/doc/pscpp-0.1.0.0 --dependency=aeson=aeson-1.4.2.0-D8uncPFaOD1BKFkUIGYQ4 --dependency=base=base-4.12.0.0 --dependency=base-compat=base-compat-0.10.5-FRXoAxOVtbG2qLNIZm1tTr --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=directory=directory-1.3.3.0 --dependency=file-embed=file-embed-0.0.11-4IE3sw0bCLQ7xXwEGMUYke --dependency=filemanip=filemanip-0.3.6.3-4hKR1ShzFTGAHrDN0hvHvS --dependency=filepath=filepath-1.4.2.1 --dependency=gitrev=gitrev-1.3.1-28bODUJmuLsJT3tLybQkQz --dependency=monad-parallel=monad-parallel-0.7.2.3-7kTh0TGJHiEEqaAnGfqnIO --dependency=mtl=mtl-2.2.2 --dependency=pattern-arrows=pattern-arrows-0.0.2-KI9DoUJvCyqIJfTPZWtjph --dependency=process=process-1.6.5.0 --dependency=protolude=protolude-0.2.3-6EKDEuuh3ZRFm0XjK4luPw --dependency=purescript=purescript-0.13.8-DmXwiIJTb1A2UhtJDLBhdh --dependency=safe=safe-0.3.17-43oyx4B630gDZMbTh3Ttji --dependency=text=text-1.2.3.1 --dependency=transformers=transformers-0.5.6.2 --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure (-6)
```

I got that same error multiple times, then it finally built.

**Comment by yairchu** [comment] 2021-01-11 17:37
Hi everyone! @akhoroshev has found the cause and contributed a fix for this, please try again with the latest `main` and if the problem still exists, feel free to re-open ❤️

**Closed as completed by yairchu** 2021-01-11 17:37 UTC
